
ycsi:
  cloud_secret:
    id: ${ yandex_csi_driver_sa_sa.id }
    service_account_id: ${ yandex_csi_driver_sa_sa.service_account_id }
    created_at: ${ yandex_csi_driver_sa_sa.created_at }
    key_algorithm: ${ yandex_csi_driver_sa_sa.key_algorithm }
    public_key: |-
      ${ indent(6 ,yandex_csi_driver_sa_sa.public_key) }
    private_key: |-
      ${ indent(6 ,yandex_csi_driver_sa_sa.private_key) }
  folder_id: ${ yandex_csi_driver_sa_sa.folder_id }

sidecars:
  provisioner:
    image:
      pullPolicy: IfNotPresent
      repository: k8s.gcr.io/sig-storage/csi-provisioner
      tag: v3.1.0

    extraArgs:
      v: 5
      capacity-ownerref-level: 2
      worker-threads: 10
      default-fstype: ext4
      timeout: 600s
      feature-gates: "Topology=true"
      enable-capacity: true
      strict-topology: true

    resources: {}
    securityContext: {}

    # terminationMessagePath: /dev/termination-log
    # terminationMessagePolicy: File


  attacher:
    image: 
      pullPolicy: IfNotPresent
      repository: k8s.gcr.io/sig-storage/csi-attacher
      tag: v3.4.0

    extraArgs:
      v: 5
      timeout: 600s
      worker-threads: 10

    resources: {}
    securityContext: {}

    # terminationMessagePath: /dev/termination-log
    # terminationMessagePolicy: File

  resizer:
    image: 
      pullPolicy: IfNotPresent
      repository: k8s.gcr.io/sig-storage/csi-resizer
      tag: v1.5.0

    extraArgs:
      v: 5
      timeout: 600s
      workers: 10

    resources: {}
    securityContext: {}

    # terminationMessagePath: /dev/termination-log
    # terminationMessagePolicy: File


  snapshotter:
    image: 
      pullPolicy: IfNotPresent
      repository: k8s.gcr.io/sig-storage/csi-snapshotter
      tag: v5.0.1

    extraArgs:
      v: 5
      timeout: 600s
      worker-threads: 10

    resources: {}
    securityContext: {}

    # terminationMessagePath: /dev/termination-log
    # terminationMessagePolicy: File

  livenessprobe:
    image: 
      pullPolicy: IfNotPresent
      repository: k8s.gcr.io/sig-storage/livenessprobe
      tag: v2.5.0

    extraArgs: {}
    resources: {}
    securityContext: {}

    # terminationMessagePath: /dev/termination-log
    # terminationMessagePolicy: File

image: 
  pullPolicy: IfNotPresent
  repository: dobrykot/cluster-csi-controller
  # Overrides the image tag whose default is v{{ .Chart.AppVersion }}
  tag: ""

defaults:
  resources:
    requests:
      ephemeral-storage: 50Mi
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File

  csiPath: /csi
  csiSockName: csi.sock
  kubeletPath: /var/lib/kubelet

controller:
  ports:
    healthPort: 12001
    addressPort: 12002

  extraArgs: {}
  resources: {}

node:
  extraArgs:
    v: 5

  extraArgs: {}
  resources: {}
  securityContext: {}

provider:
  type: YandexCloud
  name: yandex

