# NOTE: this manifest is only compatible with Kubernetes versions >=v1.21

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yandex-cloud-controller-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yandex-cloud-controller-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: yandex-cloud-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yandex-cloud-controller-manager
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: yandex-cloud-controller-manager
      containers:
      - args:
          - --leader-elect=true
          - --cluster-cidr={{ .Values.pod_cidr }}
          - --allocate-node-cidrs=true
          - --configure-cloud-routes=true
          - --cloud-provider=yandex
          - --cluster-name={{ .Values.cluster_name }}
          - --bind-address=$(BIND_IP)
          - --secure-port=64321
          - --v=2
        env:
          - name: BIND_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: YANDEX_CLUSTER_NAME
            value: {{ .Values.cluster_name }}
          - name: YANDEX_CLOUD_SERVICE_ACCOUNT_JSON
            valueFrom:
              secretKeyRef:
                name: yandex-cloud
                key: service-account-json
          - name: YANDEX_CLOUD_DEFAULT_LB_LISTENER_SUBNET_ID
          - name: YANDEX_CLOUD_DEFAULT_LB_TARGET_GROUP_NETWORK_ID
            valueFrom:
              secretKeyRef:
                name: yandex-cloud
                key: vpc-id   
          - name: KUBERNETES_SERVICE_HOST
            value: "{{ .Values.k8s_api_server }}"
          - name: KUBERNETES_SERVICE_PORT_HTTPS
            value: "{{ .Values.k8s_api_server_port }}"
          - name: YANDEX_CLOUD_INTERNAL_NETWORK_IDS
            valueFrom:
              secretKeyRef:
                name: yandex-cloud
                key: vpc-id   
          - name: YANDEX_CLOUD_EXTERNAL_NETWORK_IDS
          - name: YANDEX_CLOUD_ROUTE_TABLE_ID
            valueFrom:
              secretKeyRef:
                name: yandex-cloud
                key: route_table_id
        image: registry.deckhouse.io/deckhouse/ce:bfbae39acd8fbe3ecb8b287214357906dd2815a805f5b56d548c48c9-1663920311654
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: yandex-yandex-cloud-controller-manager
        ports:
        - containerPort: 64321
          hostPort: 64321
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 60Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      hostNetwork: true
      dnsPolicy: ClusterFirst
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: yandex-cloud-controller-manager
      serviceAccountName: yandex-cloud-controller-manager
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""