apiVersion: machine.sapcloud.io/v1alpha1
kind: YandexMachineClass
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook-weight: "3"
spec:
  bootDiskSpec:
    autoDelete: true
    imageID: {{ .Values.image_id }}
    size: 21474836480
    typeID: network-hdd
  labels:
    project: cms-production
    severity: critical
  networkInterfaceSpecs:
  - assignPublicIPAddress: true
    subnetID: {{ .Values.subnet_id }}
  networkType: STANDARD
  platformID: standard-v3
  regionID: ru-central1
  resourcesSpec:
    coreFraction: 20
    cores: 4
    memory: 8589934592
  schedulingPolicy: {}
  secretRef:
    name: treska-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  zoneID: {{ .Values.zone }}
