apiVersion: machine.sapcloud.io/v1alpha1
kind: YandexMachineClass
metadata:
  name: {{ .Values.zone }}
  namespace: {{ .Release.Namespace }}
spec:
  bootDiskSpec:
    autoDelete: true
    imageID: fd8kdq6d0p8sij7h5qe3
    size: 21474836480
    typeID: network-hdd
  labels:
    project: cms-production
    severity: critical
  networkInterfaceSpecs:
  - assignPublicIPAddress: true
    subnetID: {{ .Values.subnet_id }}
  networkType: STANDARD
  platformID: standard-v3
  regionID: ru-central1
  resourcesSpec:
    coreFraction: 20
    cores: 4
    memory: 8589934592
  schedulingPolicy: {}
  secretRef:
    name: treska
    namespace: {{ .Release.Namespace }}
  zoneID: {{ .Values.zone }}
