kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "cluster-csi-node.name" . }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "cluster-csi-node.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cluster-csi-node.name" . }}
    spec:
      serviceAccountName: {{ include "cluster-csi-node.name" . }}
      hostNetwork: true
      tolerations:
        - operator: Exists
      containers:
        - name: {{ include "cluster-csi-node.name" . }}-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/yandex.csi.flant.com/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: {{ include "cluster-csi-node.name" . }}
          securityContext:
            privileged: true
          image: registry.deckhouse.io/yandex-csi-driver/yandex-csi-driver:v0.9.11
          args:
            - "--endpoint=unix:/csi/csi.sock"
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /csi
            - name: device-dir
              mountPath: /dev
          env:
            - name: YANDEX_AUTH_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-csi-controller.name" . }}
                  key: serviceAccountJSON
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v2.0.0
          args:
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/yandex.csi.flant.com/
            type: DirectoryOrCreate
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory